FROM debian

RUN apt update
RUN apt install -y python3.9 && apt install -y python3-pip
RUN apt install -y git
RUN pip install discord.py
RUN pip install flake8
RUN apt isntall -y openjdk-17-jdk
RUN apt install -y graphviz
RUN mkdir /home/Dev